# [Dataset]
# constellation_file = "./starlink.json"

[Network]
port = 12340

[Display]
orbit = true
connection = true

[Simulation]
time_speed = 1.0
connection_distance = 2000.0
connection_number = 4